source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'LXPageViewWithButtonsViewController_Example' do
      pod 'LXPageViewWithButtonsViewController', :path => '../'

    target 'LXPageViewWithButtonsViewController_Tests' do
        inherit! :search_paths
    end
end
